[project]
site_name = "LAAC-LSCP Models"
site_url = "https://labicquette.github.io/babyhubertdocumentation/"
site_description = "A deep learning model for classifying speakers in child-centered long-form audio recordings."
site_author = "LAAC-LSCP"
copyright = "&copy; 2026 LAAC-LSCP, ENS-PSL"

nav = [
    { "VTC2.0" = [
        "https://arxaqapi.github.io/LAAC-LSCP-documentation/"
    ]},
    
    { "BabyHuBERT" = [
        {"Home" = "index.md"},
        { "One pager" = "one_pager.md" },
        { "Ethics" = [
            "ethics/ethics.md",
        ] },
        { "Advanced" = [
            "advanced/representations.md",
        ] },
    ]},

    { "Addressee" = [
        "https://labicquette.github.io/babyhubertdocumentation/"
    ]},
]

[project.theme]
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.instant",
    "navigation.path",
    "navigation.top",
    "navigation.footer",
    # "navigation.instant.preview", # experimental :/
    "toc.follow",
    "content.code.copy",
]
favicon = "assets/baby.png"
[project.theme.icon]
logo = "lucide/baby"
# logo = "assets/favicon_256.png"

[project.theme.palette]
# scheme = "slate"
primary = "green"
accent = "green"

[project.extra]
repo_url = "https://github.com/LAAC-LSCP/VTC"
repo_name = "LAAC-LSCP/VTC"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/LAAC-LSCP/VTC"
name = "VTC GitHub repository"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/"
name = "VTC PyPI page"
